### ISSUE TITLE
Byte_size parameter provided in the bulk settings is totally ignored

### ISSUE THREAD

**Issue by kamalsharma9001** [dadoonet/fscrawler#1835] opened 2024-03-15 13:18 UTC
```
The byte_size in the bulk settings is ignored and it is not used while ingesting the data in to elasticsearch.

In the Bulk Settings there are three parameters namely bulk_size, byte_size and flush_interval. 
While ingesting data into Elasticsearch, the bulk_size is taken into account and the byte_size is totally ignored.

config in _settings.json file:
 "elasticsearch" : {
    "nodes" : [ {
	  "url": "https://localhost:9200"
    } ],
	"bulk_size": 100,
	"byte_size": "5mb",
       "flush_interval": "5s",
	"username": "elastic",
	"password": "Elastic@987",
	"index": "test-data-000001"
  },

```

**Comment by dadoonet** [comment] 2024-03-15 19:08
Yes that's true. It's a bug (in fact a regression) caused by the switch from the official rest client to our own implementation.

**Comment by arima-chandran** [comment] 2024-03-26 13:16
We have modified the code for FsCrawlerBulkProcessor for the byte_size scenario. We have tested for the parameter bulk_size: 3 and byte_size : 3kb and the bulk processor works when either of the condition is satisfied. Please find attached the trace logs and let us know where we need to push the code in github.
[TraceLogs.txt](https://github.com/dadoonet/fscrawler/files/14758877/TraceLogs.txt)

**Comment by kamalsharma9001** [comment] 2024-03-26 13:22
We have modified the code for FsCrawlerBulkProcessor for the byte_size scenario. We have tested for the parameter bulk_size: 3 and byte_size : 3kb and the bulk processor works when either of the condition is satisfied. Please find attached the trace logs and let us know where we need to push the code in github.
[TraceLogs.txt](https://github.com/dadoonet/fscrawler/files/14758984/TraceLogs.txt)

**Comment by dadoonet** [comment] 2024-03-26 13:37
Great! Could you push your branch on your repository and then create a pull request from it?

**Comment by kamalsharma9001** [comment] 2024-03-27 08:07
we have created a repository name kamalsharma9001/fscrawler-1 and the branch name is kamal-issue-1835. We have raised a pull request. Please check and let us know.

**Comment by kamalsharma9001** [comment] 2024-03-28 10:24
We have created new pull request with repository name kamalsharma9001/fscrawler-1 and the branch name as crawler-issue-change-1835. We have modified code as per your comments. Please check and let us know.

**Comment by dadoonet** [comment] 2024-03-28 10:25
Does it mean that you want to close this PR?

**Comment by kamalsharma9001** [comment] 2024-03-28 10:55
committed changes in last pull request as per your comments. Please check

**Closed** 2024-03-29 16:07 UTC
Labels: bug
