### ISSUE TITLE
fscrawler 2.4 not deleting indexes

### ISSUE THREAD

**Issue by mayer4** [dadoonet/fscrawler#621] opened 2018-10-19 14:38 UTC
Hello,

Our developer left and I have been tasked with maintaining his code. He installed elastic search and fscrawler. I'm not sure if it ever worked, but when I run it with the following attached code it doesn't update the index to reflect deleted files. Is it the code or the version that is making it not reflect the changes? 

Thanks
[_settings.txt](https://github.com/dadoonet/fscrawler/files/2496254/_settings.txt)

 for any help

Laura

**Comment by dadoonet** [comment] 2018-10-22 10:54
This might have been fixed with 2.5. See for example #409.
Please upgrade and if the problem is still there reopen this issue (or just comment here).

Thanks! 
I'm closing for now.

**Closed by dadoonet** 2018-10-22 10:54 UTC

**Comment by mayer4** [comment] 2018-10-22 17:12
Hello,

I tried upgrading to 2.5 and followed the directions in the upgrade notes. It will not reindex anything now. I am getting the message Mapping is incorrect: please set stored: true on field [file.filename]. I don't see settings in my _settings.json for that. Nor do I see where to set it. Sorry for the questions, I just got stuck with this and have no idea what to do with it.  

Laura

**Comment by dadoonet** [comment] 2018-10-22 17:18
Can you run fscrawler with `--debug` option and paste all logs here?

**Comment by mayer4** [comment] 2018-10-22 17:28
Sure thing, Thank you for your help. 
[file.txt](https://github.com/dadoonet/fscrawler/files/2502428/file.txt)

**Comment by dadoonet** [comment] 2018-10-22 17:49
I see. Easiest way to fix it is to reindex from the begining. Is that possible for you?
If so, delete the existing indices and run the job again with the `--restart` option.

It should create again the right mappings...

**Comment by mayer4** [comment] 2018-10-22 17:52
Like so:

fscrawler forms --config_dir D:\FSCrawler --restart 

I get the same message and then it just stops all together.

**Comment by dadoonet** [comment] 2018-10-22 19:34
Did you remove the indices first?

**Comment by mayer4** [comment] 2018-10-22 19:47
I don't know how to do that sorry. 

Thanks for all your help. I really appreciate it.  I think this is way to hard for me to manage and I'll just try something else. Thank you again.

**Comment by dadoonet** [comment] 2018-10-22 19:57
Have a look at https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-delete-index.html

**Comment by mayer4** [comment] 2018-10-23 11:52
Thanks for that. I'll take a look.
