### ISSUE TITLE
Will this warning affect the functionality of fscrawler/ES?

### ISSUE THREAD

**Issue by cnddu** [dadoonet/fscrawler#370] opened 2017-05-17 06:58 UTC
Bellow are the logs:

```
[cmgc@iZ28vryf5hjZ fscrawler-2.3-SNAPSHOT]$ bin/fscrawler 
14:45:11,262 INFO  [f.p.e.c.f.FsCrawler] No job specified. Here is the list of existing jobs:
14:45:11,268 INFO  [f.p.e.c.f.FsCrawler] [1] - mdtest
14:45:11,268 INFO  [f.p.e.c.f.FsCrawler] Choose your job [1-1]...
1
14:45:20,145 INFO  [f.p.e.c.f.FsCrawlerImpl] Starting FS crawler
14:45:20,145 INFO  [f.p.e.c.f.FsCrawlerImpl] FS crawler started in watch mode. It will run unless you stop it with CTRL+C.
**14:45:20,810 WARN  [o.e.c.RestClient] request [PUT http://127.0.0.1:9200/mdtest] returned 1 warnings: [299 Elasticsearch-5.4.0-780f8c4 "Content type detection for rest requests is deprecated. Specify the content type using the [Content-Type] header." "Wed, 17 May 2017 06:45:20 GMT"]**
14:45:20,845 INFO  [f.p.e.c.f.FsCrawlerImpl] FS crawler started for [mdtest] for [/home/cmgc/docs] every [15m]
```

**Comment by dadoonet** [comment] 2017-05-17 07:14
No. Duplicate of #354

The latest SNAPSHOT should not have this message anymore.

**Closed by dadoonet** 2017-05-17 07:14 UTC
