### ISSUE TITLE
fscrawler 2.1: incompatible settings.json leads to prompting to create new project

### ISSUE THREAD

**Issue by shadiakiki1986** [dadoonet/fscrawler#284] opened 2017-01-24 11:12 UTC
Upon adding `bulksize` to the config settings (e.g. [here](https://github.com/shadiakiki1986/docker-fscrawler/compare/4607f84db325...bb9091ec0c7f)) my travis build shows that fscrawler 2.1 started prompting for `Y/n` for creating a new project, (check logs [here](https://travis-ci.org/shadiakiki1986/docker-fscrawler/jobs/194774405#L621))

**Comment by dadoonet** [comment] 2017-01-30 15:56
Thank you for reporting.

I'm not able to reproduce it. See https://github.com/dadoonet/fscrawler/issues/290#issuecomment-276100834

**Comment by dadoonet** [comment] 2017-01-30 15:57
I'm closing in favor of #290 as I already commented there.

**Closed by dadoonet** 2017-01-30 15:57 UTC

**Comment by dadoonet** [comment] 2017-01-31 16:59
I think actually that I fixed the issue (not exactly the issue but kind of) with #295.
It now exists and gives a stacktrace of the problem.

**Comment by shadiakiki1986** [comment] 2017-01-31 18:10
Thanks @dadoonet ! I already started using `fscrawler` and it's great! :)
