### ISSUE TITLE
fscrawler not creating or running the newly created job

### ISSUE THREAD

**Issue by dgilbert002** [dadoonet/fscrawler#294] opened 2017-01-31 16:09 UTC
been trying to run a job that i've configured and get the following exception. Running on Windows 7, using version 2.2. I've noted that it always asks to create the job as well - no resuming

```
C:\ELK-Stack\fscrawler\bin>fscrawler
20:04:26,992 ←[32mINFO ←[m [f.p.e.c.f.FsCrawler] No job specified. Here is the list of existing jobs:
20:04:26,999 ←[32mINFO ←[m [f.p.e.c.f.FsCrawler] [1] - first_test
20:04:27,002 ←[32mINFO ←[m [f.p.e.c.f.FsCrawler] [2] - test
20:04:27,003 ←[32mINFO ←[m [f.p.e.c.f.FsCrawler] Choose your job [1-2]...
1
20:04:31,172 ←[33mWARN ←[m [f.p.e.c.f.FsCrawler] job [first_test] does not exist
20:04:31,173 ←[32mINFO ←[m [f.p.e.c.f.FsCrawler] Do you want to create it (Y/N)?

y
Exception in thread "main" java.lang.NullPointerException
        at fr.pilato.elasticsearch.crawler.fs.FsCrawler.main(FsCrawler.java:215)
```

```
C:\ELK-Stack\fscrawler\bin>fscrawler
20:05:46,162 ←[32mINFO ←[m [f.p.e.c.f.FsCrawler] No job specified. Here is the list of existing jobs:
20:05:46,168 ←[32mINFO ←[m [f.p.e.c.f.FsCrawler] [1] - first_test
20:05:46,169 ←[32mINFO ←[m [f.p.e.c.f.FsCrawler] [2] - test
20:05:46,169 ←[32mINFO ←[m [f.p.e.c.f.FsCrawler] Choose your job [1-2]...
1
20:05:51,571 ←[33mWARN ←[m [f.p.e.c.f.FsCrawler] job [first_test] does not exist

20:05:51,573 ←[32mINFO ←[m [f.p.e.c.f.FsCrawler] Do you want to create it (Y/N)?

y
Exception in thread "main" java.lang.NullPointerException
        at fr.pilato.elasticsearch.crawler.fs.FsCrawler.main(FsCrawler.java:215)


C:\ELK-Stack\fscrawler\bin>
```

**Comment by dadoonet** [comment] 2017-01-31 16:18
Thanks for reporting! This is a bug indeed.

**Comment by dadoonet** [comment] 2017-01-31 16:20
Apparently this does not reproduce on MacOS. Let me try on a windows instance.

**Comment by dadoonet** [comment] 2017-01-31 16:21
BTW can you run the same command with `--trace` option please?

**Comment by dgilbert002** [comment] 2017-01-31 16:22
Sure...

Results below:

C:\ELK-Stack\fscrawler\bin>fscrawler --trace
20:21:47,840 ←[36mDEBUG←[m [f.p.e.c.f.u.FsCrawlerUtil] Mapping [1/doc.json] alre
ady exsits
20:21:47,842 ←[36mDEBUG←[m [f.p.e.c.f.u.FsCrawlerUtil] Mapping [1/folder.json] a
lready exsits
20:21:47,844 ←[36mDEBUG←[m [f.p.e.c.f.u.FsCrawlerUtil] Mapping [1/_settings.json
] already exsits
20:21:47,846 ←[36mDEBUG←[m [f.p.e.c.f.u.FsCrawlerUtil] Mapping [2/doc.json] alre
ady exsits
20:21:47,847 ←[36mDEBUG←[m [f.p.e.c.f.u.FsCrawlerUtil] Mapping [2/folder.json] a
lready exsits
20:21:47,848 ←[36mDEBUG←[m [f.p.e.c.f.u.FsCrawlerUtil] Mapping [2/_settings.json
] already exsits
20:21:47,849 ←[36mDEBUG←[m [f.p.e.c.f.u.FsCrawlerUtil] Mapping [5/doc.json] alre
ady exsits
20:21:47,850 ←[36mDEBUG←[m [f.p.e.c.f.u.FsCrawlerUtil] Mapping [5/folder.json] a
lready exsits
20:21:47,851 ←[36mDEBUG←[m [f.p.e.c.f.u.FsCrawlerUtil] Mapping [5/_settings.json
] already exsits
20:21:47,853 ←[32mINFO ←[m [f.p.e.c.f.FsCrawler] No job specified. Here is the l
ist of existing jobs:
20:21:47,856 ←[36mDEBUG←[m [f.p.e.c.f.u.FsCrawlerUtil] Adding job [first_test]
20:21:47,856 ←[36mDEBUG←[m [f.p.e.c.f.u.FsCrawlerUtil] Adding job [test]
20:21:47,858 ←[36mDEBUG←[m [f.p.e.c.f.u.FsCrawlerUtil] Ignoring [_default] dir a
s no [_settings.json]áhas been found
20:21:47,859 ←[32mINFO ←[m [f.p.e.c.f.FsCrawler] [1] - first_test
20:21:47,860 ←[32mINFO ←[m [f.p.e.c.f.FsCrawler] [2] - test
20:21:47,861 ←[32mINFO ←[m [f.p.e.c.f.FsCrawler] Choose your job [1-2]...
1
20:21:50,986 ←[36mDEBUG←[m [f.p.e.c.f.FsCrawler] Starting job [first_test]...
20:21:51,086 ←[33mWARN ←[m [f.p.e.c.f.FsCrawler] job [first_test] does not exist

20:21:51,087 ←[32mINFO ←[m [f.p.e.c.f.FsCrawler] Do you want to create it (Y/N)?

y
Exception in thread "main" java.lang.NullPointerException
        at fr.pilato.elasticsearch.crawler.fs.FsCrawler.main(FsCrawler.java:215)


C:\ELK-Stack\fscrawler\bin>

**Comment by dadoonet** [comment] 2017-01-31 16:46
Can you try this version? https://oss.sonatype.org/content/repositories/snapshots/fr/pilato/elasticsearch/crawler/fscrawler/2.2-SNAPSHOT/fscrawler-2.2-20170131.164351-144.zip

It should fail but with a much more interesting trace.

**Comment by dgilbert002** [comment] 2017-01-31 16:54
see below:

C:\ELK-Stack\fscrawler\bin>fscrawler --trace
20:53:53,205 ←[36mDEBUG←[m [f.p.e.c.f.u.FsCrawlerUtil] Mapping [1/doc.json] alre
ady exists
20:53:53,207 ←[36mDEBUG←[m [f.p.e.c.f.u.FsCrawlerUtil] Mapping [1/folder.json] a
lready exists
20:53:53,208 ←[36mDEBUG←[m [f.p.e.c.f.u.FsCrawlerUtil] Mapping [1/_settings.json
] already exists
20:53:53,209 ←[36mDEBUG←[m [f.p.e.c.f.u.FsCrawlerUtil] Mapping [2/doc.json] alre
ady exists
20:53:53,209 ←[36mDEBUG←[m [f.p.e.c.f.u.FsCrawlerUtil] Mapping [2/folder.json] a
lready exists
20:53:53,209 ←[36mDEBUG←[m [f.p.e.c.f.u.FsCrawlerUtil] Mapping [2/_settings.json
] already exists
20:53:53,210 ←[36mDEBUG←[m [f.p.e.c.f.u.FsCrawlerUtil] Mapping [5/doc.json] alre
ady exists
20:53:53,210 ←[36mDEBUG←[m [f.p.e.c.f.u.FsCrawlerUtil] Mapping [5/folder.json] a
lready exists
20:53:53,210 ←[36mDEBUG←[m [f.p.e.c.f.u.FsCrawlerUtil] Mapping [5/_settings.json
] already exists
20:53:53,213 ←[32mINFO ←[m [f.p.e.c.f.FsCrawler] No job specified. Here is the l
ist of existing jobs:
20:53:53,214 ←[36mDEBUG←[m [f.p.e.c.f.u.FsCrawlerUtil] Adding job [first_test]
20:53:53,214 ←[36mDEBUG←[m [f.p.e.c.f.u.FsCrawlerUtil] Adding job [test]
20:53:53,214 ←[36mDEBUG←[m [f.p.e.c.f.u.FsCrawlerUtil] Ignoring [_default] dir a
s no [_settings.json]áhas been found
20:53:53,215 ←[32mINFO ←[m [f.p.e.c.f.FsCrawler] [1] - first_test
20:53:53,215 ←[32mINFO ←[m [f.p.e.c.f.FsCrawler] [2] - test
20:53:53,215 ←[32mINFO ←[m [f.p.e.c.f.FsCrawler] Choose your job [1-2]...
1
20:53:54,902 ←[36mDEBUG←[m [f.p.e.c.f.FsCrawler] Starting job [first_test]...
Exception in thread "main" com.fasterxml.jackson.databind.JsonMappingException:
Unexpected character ('"' (code 34)): was expecting comma to separate Object ent
ries
 at [Source: {
  "name" : "test",
  "fs" : {
    "url" : "C:\\FS_test\\",
    "update_rate" : "15m",
    "includes": [
      "*.*"
    ],
    "excludes": [
      "*.json"
    ],
    "json_support" : false,
    "xml_support" : false,
    "ignore_folders" : false,
    "attributes_support" : true,
    "raw_metadata" : true,
    "filename_as_id" : true,
    "add_filesize" : true,
    "remove_deleted" : true,
    "store_source" : false,
    "lang_detect" : false,
    "indexed_chars" : "-1"
    "checksum": "MD5"
  },
  "elasticsearch" : {
    "nodes" : [ {
      "host" : "127.0.0.1",
      "port" : 9200,
      "scheme" : "HTTP"
    } ],
    "index" : "docs",
    "type" : "doc",
    "bulk_size" : 100,
    "flush_interval" : "5s",
    "username" : "",
    "password" : "",
    "pipeline" : ""
  }
}; line: 23, column: 6]
 at [Source: {
  "name" : "test",
  "fs" : {
    "url" : "C:\\FS_test\\",
    "update_rate" : "15m",
    "includes": [
      "*.*"
    ],
    "excludes": [
      "*.json"
    ],
    "json_support" : false,
    "xml_support" : false,
    "ignore_folders" : false,
    "attributes_support" : true,
    "raw_metadata" : true,
    "filename_as_id" : true,
    "add_filesize" : true,
    "remove_deleted" : true,
    "store_source" : false,
    "lang_detect" : false,
    "indexed_chars" : "-1"
    "checksum": "MD5"
  },
  "elasticsearch" : {
    "nodes" : [ {
      "host" : "127.0.0.1",
      "port" : 9200,
      "scheme" : "HTTP"
    } ],
    "index" : "docs",
    "type" : "doc",
    "bulk_size" : 100,
    "flush_interval" : "5s",
    "username" : "",
    "password" : "",
    "pipeline" : ""
  }
}; line: 22, column: 23] (through reference chain: fr.pilato.elasticsearch.crawl
er.fs.meta.settings.FsSettings["fs"])
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(Json
MappingException.java:379)
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(Json
MappingException.java:339)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThro
w(BeanDeserializerBase.java:1589)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserial
ize(BeanDeserializer.java:278)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(Bea
nDeserializer.java:140)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMa
pper.java:3789)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.ja
va:2833)
        at fr.pilato.elasticsearch.crawler.fs.meta.settings.FsSettingsParser.fro
mJson(FsSettingsParser.java:34)
        at fr.pilato.elasticsearch.crawler.fs.meta.settings.FsSettingsFileHandle
r.read(FsSettingsFileHandler.java:47)
        at fr.pilato.elasticsearch.crawler.fs.FsCrawler.main(FsCrawler.java:184)

Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character (
'"' (code 34)): was expecting comma to separate Object entries
 at [Source: {
  "name" : "test",
  "fs" : {
    "url" : "C:\\FS_test\\",
    "update_rate" : "15m",
    "includes": [
      "*.*"
    ],
    "excludes": [
      "*.json"
    ],
    "json_support" : false,
    "xml_support" : false,
    "ignore_folders" : false,
    "attributes_support" : true,
    "raw_metadata" : true,
    "filename_as_id" : true,
    "add_filesize" : true,
    "remove_deleted" : true,
    "store_source" : false,
    "lang_detect" : false,
    "indexed_chars" : "-1"
    "checksum": "MD5"
  },
  "elasticsearch" : {
    "nodes" : [ {
      "host" : "127.0.0.1",
      "port" : 9200,
      "scheme" : "HTTP"
    } ],
    "index" : "docs",
    "type" : "doc",
    "bulk_size" : 100,
    "flush_interval" : "5s",
    "username" : "",
    "password" : "",
    "pipeline" : ""
  }
}; line: 23, column: 6]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java
:1702)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(Parser
MinimalBase.java:558)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedCh
ar(ParserMinimalBase.java:456)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipComma(Read
erBasedJsonParser.java:2286)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextFieldName(R
eaderBasedJsonParser.java:912)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserial
ize(BeanDeserializer.java:283)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(Bea
nDeserializer.java:140)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize
(SettableBeanProperty.java:490)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeA
ndSet(MethodProperty.java:95)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserial
ize(BeanDeserializer.java:276)
        ... 6 more

C:\ELK-Stack\fscrawler\bin>

**Comment by dadoonet** [comment] 2017-01-31 16:56
I see.

Can you try to set URL to `"url" : "C:\\FS_test\\"` instead?

**Comment by dgilbert002** [comment] 2017-01-31 16:58
It's running now - there was a , missing on line 23

will keep testing and revert with any issues... many thanks for the assistance

**Comment by dadoonet** [comment] 2017-01-31 17:02
Great! I'm closing as it's not really a bug. And now with #295 we have a better idea of the cause of the problem.

**Closed by dadoonet** 2017-01-31 17:02 UTC
Labels: bug

**Comment by Neel-Gagan** [comment] 2018-08-03 10:25
1) I am getting the warining  "Layout tables used in font Avenir-Light are not implemented in PDFBox and will be ignored" while running FSCrawler 2.4 using --username admin switch, but i  am not getting 
  date time of "lastrun" :  and count of   "indexed" : and   "deleted" :  items in the folder i have mapped the crawler in _status.json file under . fscrawler folder.
   kindly guide me how to get this _status.json file updated
   
2) is there any way to determine the name  of files that have been ignored by fscrawler while indexing a particular folder.

3) i am not getting match of count of number of files in a folder and indexed documents in  crawling done by fscrawler on that folder.
