### ISSUE TITLE
Crawler mixes up content from different files

### ISSUE THREAD

**Issue by j-a-a-p** [dadoonet/fscrawler#1798] opened 2024-01-12 08:17 UTC
**Describe the bug**
An empty document is crawled, the content and file node in the index are filled with the data of probably the previous parsed document.
This bug is a combination of another bug, documents starting with ~ are being included. In our text corpus it is going through.

**Job Settings**

```yml
# required
name: "abc"

# required
fs:
  # define a "local" file path crawler, if running inside a docker container this must be the path INSIDE the container
  url: "/tmp/es"
  follow_symlink: false
  remove_deleted: false
  continue_on_error: true
  update_rate: "5m"
  includes:
  - "*.pdf"
  - "*.doc"
  - "*.docx"
  - "*.xsl"
  - "*.xslx"
  - "*.msg"
  - "*.txt"
  - "*.md"
  excludes:
  - "*.exclude"
  - "~*"
  # optional: do not send big files to TIKA
  ignore_above: "512mb"

  # special handling of JSON files, should only be used if ALL files are JSON
  json_support: false
  add_as_inner_object: false
  xml_support: false
  filename_as_id: false
  add_filesize: true
  # inlcude user/group of file only if needed
  attributes_support: false
  # do you REALLY want to store every file as a copy in the index ? Then set this to true
  store_source: false
  # you may want to store (partial) content of the file (see indexed_chars)
  index_content: true
  # how much data from the content of the file should be indexed (and stored inside the index), set to 0 if you need checksum, but no content at all to be indexed
  #indexed_chars: "0"
  # TODO what is the tradeoff here, if set to 0 all seems to work still
  indexed_chars: "1000000"
  # usually file metadata will be stored in separate fields, if you want to keep the original set, set this to true
  raw_metadata: false
  # optional: add checksum meta (requires index_content to be set to true)
  checksum: "MD5"
  # recommmended, but will create another index
  index_folders: false
  lang_detect: true

  ocr.pdf_strategy: noocr
  #ocr:
  #  language: "eng"
  #  path: "/path/to/tesseract/if/not/available/in/PATH"
  #  data_path: "/path/to/tesseract/tessdata/if/needed"

# optional: only required if you want to SSH to another server to index documents from there
#server:
#  hostname: "localhost"
#  port: 22
#  username: "dadoonet"
#  password: "password"
#  protocol: "SSH"
#  pem_path: "/path/to/pemfile"

# required
elasticsearch:
  nodes:
  # With Cloud ID
  # - cloud_id: "CLOUD_ID"
  # With URL
  - url: "https://es01.localhost.direct:9200"
  bulk_size: 1000
  flush_interval: "5s"
  byte_size: "10mb"
  username: "elastic"
  password: "changeme"
  # optional, defaults to "docs"
  index: "tldr_index_docs"
  # optional, defaults to "test_folders", used when es.index_folders is set to true
  # index_folder: "test_fold"
  ssl_verification: true
  pipeline: "fscrawler"
rest:
  # only is started with --rest option
  url: "http://localhost:8080/fscrawler"
  enable_cors: true
```

**Logs**

```
FULL FSCrawler LOGS HERE
```

**Expected behavior**
Make sure data of files are not being mixed up.

**Versions:**
Mac
version 10

**Attachment**

If the bug is related to a given file, please share this file, so we can reuse it in tests
to reproduce the problem and may be use it in our integration tests.

**Comment by dadoonet** [comment] 2024-01-12 08:41
Great finding! Let me add a test and a fix for this.

**Comment by dadoonet** [comment] 2024-01-12 13:29
So I tried to reproduce the issue but with no luck so far.

I'm indexing a first document `01-not-empty.txt` which contains `Hello world` and then a second one `02-empty.txt` which is empty.

As a result, I'm seeing:

```
GET fscrawler_fs_crawler_test_empty_files_i_t_test_empty_files/_search
```

```json
{
  "took": 1,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 2,
      "relation": "eq"
    },
    "max_score": 1,
    "hits": [
      {
        "_index": "fscrawler_fs_crawler_test_empty_files_i_t_test_empty_files",
        "_id": "23f5da98a61d207ac02723f85414c0",
        "_score": 1,
        "_source": {
          "content": """Hello world

""",
          "file": {
            "extension": "txt",
            "content_type": "text/plain; charset=ISO-8859-1",
            "created": "2024-01-12T13:24:24.000+00:00",
            "last_modified": "2024-01-12T13:24:24.346+00:00",
            "last_accessed": "2024-01-12T13:24:24.356+00:00",
            "indexing_date": "2024-01-12T13:24:24.606+00:00",
            "filesize": 12,
            "filename": "01-not-empty.txt",
            "url": "file:///var/folders/xn/47mdpxd12vq4zrjhkwbhd5_r0000gn/T/junit307035750893341835/resources/test_empty_files/01-not-empty.txt"
          },
          "path": {
            "root": "c794792f386a076532c97ad368d4c1",
            "virtual": "/01-not-empty.txt",
            "real": "/var/folders/xn/47mdpxd12vq4zrjhkwbhd5_r0000gn/T/junit307035750893341835/resources/test_empty_files/01-not-empty.txt"
          }
        }
      },
      {
        "_index": "fscrawler_fs_crawler_test_empty_files_i_t_test_empty_files",
        "_id": "7ce7eff2d74c1c8f753917afe8645ae9",
        "_score": 1,
        "_source": {
          "file": {
            "extension": "txt",
            "content_type": "text/plain",
            "created": "2024-01-12T13:24:24.000+00:00",
            "last_modified": "2024-01-12T13:24:24.345+00:00",
            "last_accessed": "2024-01-12T13:24:24.345+00:00",
            "indexing_date": "2024-01-12T13:24:24.761+00:00",
            "filesize": 0,
            "filename": "02-empty.txt",
            "url": "file:///var/folders/xn/47mdpxd12vq4zrjhkwbhd5_r0000gn/T/junit307035750893341835/resources/test_empty_files/02-empty.txt"
          },
          "path": {
            "root": "c794792f386a076532c97ad368d4c1",
            "virtual": "/02-empty.txt",
            "real": "/var/folders/xn/47mdpxd12vq4zrjhkwbhd5_r0000gn/T/junit307035750893341835/resources/test_empty_files/02-empty.txt"
          }
        }
      }
    ]
  }
}
``` 

Could you share 2 documents which reproduce the problem?

**Comment by j-a-a-p** [comment] 2024-01-12 13:44
Here is my response from ES (redacted by hand, so probably not valid anymore):
// 20240112143800
// https://localhost:9200/tldr_index_docs/_search

{
  "took": 10,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 14,
      "relation": "eq"
    },
    "max_score": 1.0,
    "hits": [
      {
        "_index": "tldr_index_docs",
        "_id": "a19e70123b9fa6c081cbb1b215cec9",
        "_score": 1.0,
        "_ignored": [
          "ai.summary.keyword"
        ],
        "_source": {
          "path": {
            "virtual": "/hr/Employement contract Sam Weller.docx",
            "root": "b12eb5e0d593dd6dfaabe8c41975ba6a",
            "real": "/tmp/es/hr/Employement contract Sam Weller.docx"
          },
          "file": {
            "extension": "docx",
            "last_accessed": "2023-12-20T11:07:14.610+00:00",
            "filename": "Employement contract Sam Weller.docx",
            "indexed_chars": 1000000,
            "content_type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            "created": "2023-12-19T13:52:37.472+00:00",
            "indexing_date": "2024-01-09T17:42:08.888+00:00",
            "checksum": "adc520c324262d8d428f38627865fbd7",
            "filesize": 14490,
            "last_modified": "2023-12-19T13:52:37.472+00:00",
            "url": "file:///tmp/es/hr/Employement contract Sam Weller.docx"
          },
          "meta": {
            "date": "2023-12-19T13:52:00.000+00:00",
            "author": "Jacob Marley",
            "created": "2023-12-19T13:49:00.000+00:00",
            "modifier": "Jaap Stelwagen",
            "language": "en"
          },
          "content": "EMPLOYMENT CONTRACT\nBETWEEN:\n\nBounderby's Mill\n(Hereinafter referred to as \"Employer\")\nLocated at: [Employer's Address, Berlin]\n\nAND:\nSam Weller, MSc\n(Hereinafter referred to as \"Employee\")\nBorn on: 11-2-1966\n\n1. POSITION AND DUTIES\n1.1. The Employer hereby agrees to employ Sam Weller, MSc (the \"Employee\") in the capacity of Financial Director. The Employee's duties shall be those customarily associated with such position, together with such other duties as may from time to time be assigned by the Employer.\n1.2. The Employee agrees to devote full working time and attention to the business of the Employer, and shall not engage in any other business activity, whether full-time or part-time, without the written consent of the Employer.\n\n2. SALARY AND BENEFITS\n2.1. The Employer agrees to pay the Employee a salary of EUR 180,000 per year, payable in equal monthly installments on the last business day of each month.\n2.2. In addition to the salary, the Employee will be entitled to participate in any standard employee benefit plans which the Employer offers to its employees.\n2.3. MBA Study Reimbursement: The Employer agrees to reimburse the Employee for up to EUR 80,000 for MBA studies, with the amount being reduced linearly to zero if the Employee leaves the company within three years from the commencement of the employment.\n\n3. TERM OF EMPLOYMENT\n3.1. The employment under this Agreement shall commence on 1-11-2023 and shall continue indefinitely until terminated as provided herein.\n\n4. NON-COMPETE AND CONFIDENTIALITY\n4.1. During the term of employment and for a period of [X years] thereafter, the Employee shall not, directly or indirectly, engage in any business competitive with the Employer.\n4.2. Non-Compete Penalty: In the event of breach of the non-compete clause, the Employee shall pay a fine of EUR 1,000 per day for each day of breach.\n4.3. The Employee shall not, at any time, disclose any confidential information pertaining to the business of the Employer, both during and after the term of employment.\n\n5. TERMINATION\n5.1. This Agreement may be terminated by either party by giving [X months] written notice or payment in lieu thereof.\n5.2. The Employer may terminate this Agreement immediately for cause, including but not limited to dishonesty, breach of confidentiality, or breach of non-compete clause.\n\n6. GENERAL PROVISIONS\n6.1. This Agreement contains the entire understanding between the parties and supersedes any prior understandings and agreements between them respecting the subject matter of this Agreement.\n6.2. Any amendments to this Agreement must be in writing and signed by both parties.\n\nIN WITNESS WHEREOF, the parties have executed this Agreement on the dates set forth below.\n\nBounderby's Mill\nBy: Jacob Marley, HR Director\nDate:\nSam Weller, MSc\nDate:\n\n\n",
        }
      },
      {
        "_index": "tldr_index_docs",
        "_id": "119be3f4617d47ed5578e222c9b2bbc",
        "_score": 1.0,
        "_ignored": [
          "ai.summary.keyword"
        ],
        "_source": {
          "path": {
            "virtual": "/filter test/~should-exclude.docx",
            "root": "eca63be720a62472998893711ed2134d",
            "real": "/tmp/es/filter test/~should-exclude.docx"
          },
          "file": {
            "extension": "docx",
            "last_accessed": "2024-01-09T15:40:10.417+00:00",
            "filename": "~should-exclude.docx",
            "indexed_chars": 1000000,
            "content_type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            "created": "2024-01-09T12:04:49.298+00:00",
            "indexing_date": "2024-01-09T17:42:08.844+00:00",
            "checksum": "adc520c324262d8d428f38627865fbd7",
            "filesize": 14490,
            "last_modified": "2024-01-09T12:04:49.298+00:00",
            "url": "file:///tmp/es/filter test/~should-exclude.docx"
          },
          "meta": {
            "date": "2023-12-19T13:52:00.000+00:00",
            "author": "Jacob Marley",
            "created": "2023-12-19T13:49:00.000+00:00",
            "modifier": "Jaap Stelwagen",
            "language": "en"
          },
          "content": "EMPLOYMENT CONTRACT\nBETWEEN:\n\nBounderby's Mill\n(Hereinafter referred to as \"Employer\")\nLocated at: [Employer's Address, Berlin]\n\nAND:\nSam Weller, MSc\n(Hereinafter referred to as \"Employee\")\nBorn on: 11-2-1966\n\n1. POSITION AND DUTIES\n1.1. The Employer hereby agrees to employ Sam Weller, MSc (the \"Employee\") in the capacity of Financial Director. The Employee's duties shall be those customarily associated with such position, together with such other duties as may from time to time be assigned by the Employer.\n1.2. The Employee agrees to devote full working time and attention to the business of the Employer, and shall not engage in any other business activity, whether full-time or part-time, without the written consent of the Employer.\n\n2. SALARY AND BENEFITS\n2.1. The Employer agrees to pay the Employee a salary of EUR 180,000 per year, payable in equal monthly installments on the last business day of each month.\n2.2. In addition to the salary, the Employee will be entitled to participate in any standard employee benefit plans which the Employer offers to its employees.\n2.3. MBA Study Reimbursement: The Employer agrees to reimburse the Employee for up to EUR 80,000 for MBA studies, with the amount being reduced linearly to zero if the Employee leaves the company within three years from the commencement of the employment.\n\n3. TERM OF EMPLOYMENT\n3.1. The employment under this Agreement shall commence on 1-11-2023 and shall continue indefinitely until terminated as provided herein.\n\n4. NON-COMPETE AND CONFIDENTIALITY\n4.1. During the term of employment and for a period of [X years] thereafter, the Employee shall not, directly or indirectly, engage in any business competitive with the Employer.\n4.2. Non-Compete Penalty: In the event of breach of the non-compete clause, the Employee shall pay a fine of EUR 1,000 per day for each day of breach.\n4.3. The Employee shall not, at any time, disclose any confidential information pertaining to the business of the Employer, both during and after the term of employment.\n\n5. TERMINATION\n5.1. This Agreement may be terminated by either party by giving [X months] written notice or payment in lieu thereof.\n5.2. The Employer may terminate this Agreement immediately for cause, including but not limited to dishonesty, breach of confidentiality, or breach of non-compete clause.\n\n6. GENERAL PROVISIONS\n6.1. This Agreement contains the entire understanding between the parties and supersedes any prior understandings and agreements between them respecting the subject matter of this Agreement.\n6.2. Any amendments to this Agreement must be in writing and signed by both parties.\n\nIN WITNESS WHEREOF, the parties have executed this Agreement on the dates set forth below.\n\nBounderby's Mill\nBy: Jacob Marley, HR Director\nDate:\nSam Weller, MSc\nDate:\n\n\n",
        }
      },
    ]
  }
}

**Comment by dadoonet** [comment] 2024-01-12 13:48
I see... `~should-exclude.docx` is actually not an empty document IMO but a word document being edited. It DOES contain the content.

So I think the issue is only due because we are not ignoring the `~*` pattern (#1794).

**Comment by j-a-a-p** [comment] 2024-01-12 13:48
Ah, sorry my bad,

I have several should-exclude docs in my test set. Normally they have a text like "This document shpuld not exclude", but somehow I managed to have the contents of another document of the test set

**Comment by j-a-a-p** [comment] 2024-01-12 13:49
> use we a

Correct, It is not fscrawler, but me who is mixing up documents...

**Closed** 2024-01-13 00:37 UTC
