### ISSUE TITLE
Starting fscrawler after removing an index and mapping results in unexpected behaviour

### ISSUE THREAD

**Issue by danyill** [dadoonet/fscrawler#137] opened 2015-12-29 08:10 UTC
fscrawler never seems to index some files. For instance I have provided 12 files but on a newly created index only 1 of these gets mapped. For a long time this was a mystery but I have now discovered the reason why... The use case is something like:
- Create a folder, copy some files to it
- Create a fscrawler json job description
- Optionally create an index/mapping
- Run the fscrawler json job
- Think, "I need to faff with my configuration and options some more"
- Modify the fscrawler json job description
- Delete the index/mapping
- Erroneously think you can now run the fscrawler job and you are starting "from scratch"

The reason this can't be done is because critical information appears to be stored in the `<<job_name>>_status.json` file. Details below.

For the first run of fscrawler it assumes a `scanDate` which is null which then means everything gets indexed and after that only items created or modified since the previous run are indexed.

``` java
Instant scanDatenew = Instant.now();
Instant scanDate = getLastDateFromMeta(fsSettings.getName());

// We only index the root directory once (first run)
// That means that we don't have a scanDate yet
if (scanDate == null) {
    indexRootDirectory(directory);
}

addFilesRecursively(fsSettings.getFs().getUrl(), scanDate);
```

`getLastDateFromMeta` returns null if the json job file for fscrawler is not present.

See [here](https://github.com/dadoonet/fscrawler/blob/master/src/main/java/fr/pilato/elasticsearch/crawler/fs/FsCrawlerImpl.java#L241-L250)

``` java
@SuppressWarnings("unchecked")
private Instant getLastDateFromMeta(String jobName) throws IOException {
    try {
        FsJob fsJob = fsJobFileHandler.read(jobName);
        return fsJob.getLastrun();
    } catch (NoSuchFileException e) {
        // The file does not exist yet
    }
    return null;
}
```

Obviously if the JSON status file already exists then null will never be returned after the first run.

This is not intuitive to the dumb user (me). What I would expect is that I could run fscrawler again without having to delete the status file. I suggest a hash or some unique identifier for the ES index be stored in the status file so that removal of the index can be detected and fscrawler runs can be clean whether or not the status file is considered.

**Comment by IntelBob** [comment] 2016-02-02 21:22
Oh wow, this perplexed me for a couple of days, to clean slate, I deleted elasticsearch data folder and restart fscrawler and it would not index anything and I couldn't figure out why for the life of me. As suggested, after I deleted `status.json` file that it starts working again. Not intuitive!

**Comment by sgoeschl** [comment] 2016-05-25 09:13
I would assume that this is a feature and not a bug - maybe allow better handling using the command line

```
fscrawler --command index job_name
fscrawler --command reindex job_name
```

**Comment by dadoonet** [comment] 2016-05-25 09:17
@sgoeschl I think it makes sense. `index` would be the default command I suppose if no one is set?

**Comment by sgoeschl** [comment] 2016-05-25 09:21
@dadoonet correct. Instead of "--command XXX" there could be a mandatory command  - so many options :-)

**Comment by dadoonet** [comment] 2016-05-25 09:36
@sgoeschl I'd prefer to keep the command as simple as possible. Starting with `bin/fscrawler`. So I like the idea of having some switches to do some advanced operations.

May be we could also change a bit the CLI dialog and add support for a `--advanced` flag which asks then the user about what he'd like to do:

```
1) index (default)
2) reindex
3) delete existing data
4) ... 
```

Something along those lines...

Might be too over engineering though...

**Comment by sgoeschl** [comment] 2016-05-25 10:26
There are many ways to skin the cat - functionality-wise requiring manual user interaction is painful when you automate things :-)

My take

* index job_name - index new/changed data (aka current behaviour)
* reindex job_name - index all data ignoring the latest modification time stamp (don't know if the command should terminate after it's work?)
* delete - deletes all documents in the corresponding ES index but keeps the ES index (deleting all documents without dropping the index is currently a PITA)
* drop - drops the ES index

So the use case would look like

```
> fscrawler delete job_name
> fscrawler reindex job_name
```

or 

```
> fscrawler drop job_name
> fscrawler index job_name
```

WDYT?

**Comment by dadoonet** [comment] 2016-05-25 12:49
`delete` is something we should never do in elasticsearch. There is now this Delete By Query plugin but we should not rely on that IMO.
`drop` is the way to go. We just need to clearly document it.

I like having optional commands.

Like:

```sh
# CLI
fscrawler
# Index
fscrawler job_name
# Same as previous
fscrawler job_name --index
# Reindex
fscrawler job_name --reindex
# Drop existing index (and data)
fscrawler job_name --drop
```

Wondering if `reindex` is actually a shortcut for `fscrawler job_name --drop --index`?

Because IMO reindexing in place will generate a lot of unneeded IO (merge of expunged Lucene segments)

**Comment by sgoeschl** [comment] 2016-05-25 16:31
Cross-cutting concerns :-)

IMHO "reindex" would be a way to sync already indexed content - something went wrong, ES & documents do not match but the index is in use and indexing all documents takes hours/days. Of course there are other ways to do this, e.g. index aliasing.

And `fscrawler job_name --drop --index` would not index any document since the 'lastModified' timestamp does not match - which is actually the root cause of this discussion :-)

IMHO the usage of "--XXX" is a bit strange - in terms of command line parsing "--XXX" is a "long option" but maybe I have written to many Ant & Maven scripts :-(

**Comment by sgoeschl** [comment] 2016-05-25 17:38
Or a much simpler approach - when the index mapping is created we can assume that all documents need to be processed

**Comment by fredericlam** [comment] 2016-10-31 19:57
Thanks @danyill, this thread saved my life

**Comment by dadoonet** [comment] 2017-01-31 17:24
I actually implemented a `--restart` option which basically erase the job status and reindex everything. See #267.
But it does not remove any existing data from elasticsearch. I hope this address most of the concerns I have seen in this thread.

I'm closing it but feel free to reopen or open a new issue if needed or if I miss something else you guys need.

**Closed by dadoonet** 2017-01-31 17:24 UTC
Labels: bug
