### ISSUE TITLE
XMLDocParser extracts empty field names

### ISSUE THREAD

**Issue by HansBambel** [dadoonet/fscrawler#1753] opened 2023-10-30 12:02 UTC
**Describe the bug**

I am trying to run fscrawler (2.10-SNAPSHOT) and feed it into opensearch using docker-containers. 
I checked that the files are present and visible in the container.

Somehow only a single document gets added. After adding `--trace` to the command I noticed that an error gets produced when trying to convert a XML document:

`Invalid UTF-8 middle byte 0xcf`. This looks similar to https://github.com/dadoonet/fscrawler/issues/269 but this was fixed already.

**Job Settings**

```yml
---
name: "sample_files"
fs:
  url: "/tmp/es"
  update_rate: "15m"
  includes:
  - "*/*.doc"
  - "*/*.docx"
  - "*/*.pdf"
  - "*/*.xml"
  json_support: false
  filename_as_id: true
  add_filesize: true
  remove_deleted: true
  add_as_inner_object: false
  store_source: false
  index_content: true
  attributes_support: false
  raw_metadata: false
  xml_support: true
  index_folders: true
  lang_detect: false
  continue_on_error: false
  ocr:
    language: "eng"
    enabled: true
    pdf_strategy: "ocr_and_text"
  follow_symlinks: false
elasticsearch:
  nodes:
  - url: "https://opensearch-node1:9200"
  bulk_size: 100
  flush_interval: "5s"
  byte_size: "10mb"
  ssl_verification: false  # true by default
  username: "admin"
  password: "admin"
```

**Logs**

```
11:48:44,813 TRACE [f.p.e.c.f.t.XmlDocParser] Converting XML document
11:48:44,813 TRACE [f.p.e.c.f.t.XmlDocParser] Converting XML document
11:48:44,817 WARN  [f.p.e.c.f.FsParserAbstract] Error while crawling /tmp/es: com.fasterxml.jackson.core.JsonParseException: Invalid UTF-8 middle byte 0xcf (at char #0, byte #-1)
11:48:44,817 WARN  [f.p.e.c.f.FsParserAbstract] Full stacktrace
java.lang.RuntimeException: com.fasterxml.jackson.core.JsonParseException: Invalid UTF-8 middle byte 0xcf (at char #0, byte #-1)
	at fr.pilato.elasticsearch.crawler.fs.tika.XmlDocParser.asMap(XmlDocParser.java:82) ~[fscrawler-tika-2.10-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.tika.XmlDocParser.generateMap(XmlDocParser.java:72) ~[fscrawler-tika-2.10-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.tika.XmlDocParser.generate(XmlDocParser.java:52) ~[fscrawler-tika-2.10-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.indexFile(FsParserAbstract.java:486) ~[fscrawler-core-2.10-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.addFilesRecursively(FsParserAbstract.java:277) ~[fscrawler-core-2.10-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.addFilesRecursively(FsParserAbstract.java:304) ~[fscrawler-core-2.10-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.FsParserAbstract.run(FsParserAbstract.java:152) [fscrawler-core-2.10-SNAPSHOT.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: com.fasterxml.jackson.core.JsonParseException: Invalid UTF-8 middle byte 0xcf (at char #0, byte #-1)
	at com.fasterxml.jackson.dataformat.xml.XmlFactory._initializeXmlReader(XmlFactory.java:734) ~[jackson-dataformat-xml-2.15.2.jar:2.15.2]
	at com.fasterxml.jackson.dataformat.xml.XmlFactory._createParser(XmlFactory.java:600) ~[jackson-dataformat-xml-2.15.2.jar:2.15.2]
	at com.fasterxml.jackson.dataformat.xml.XmlFactory._createParser(XmlFactory.java:30) ~[jackson-dataformat-xml-2.15.2.jar:2.15.2]
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:1143) ~[jackson-core-2.15.2.jar:2.15.2]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3809) ~[jackson-databind-2.15.2.jar:2.15.2]
	at fr.pilato.elasticsearch.crawler.fs.tika.XmlDocParser.asMap(XmlDocParser.java:80) ~[fscrawler-tika-2.10-SNAPSHOT.jar:?]
	... 7 more
Caused by: com.ctc.wstx.exc.WstxIOException: Invalid UTF-8 middle byte 0xcf (at char #0, byte #-1)
	at com.ctc.wstx.sr.StreamScanner.constructFromIOE(StreamScanner.java:653) ~[woodstox-core-6.5.1.jar:6.5.1]
	at com.ctc.wstx.sr.StreamScanner.loadMore(StreamScanner.java:1017) ~[woodstox-core-6.5.1.jar:6.5.1]
	at com.ctc.wstx.sr.StreamScanner.getNext(StreamScanner.java:770) ~[woodstox-core-6.5.1.jar:6.5.1]
	at com.ctc.wstx.sr.BasicStreamReader.nextFromProlog(BasicStreamReader.java:2096) ~[woodstox-core-6.5.1.jar:6.5.1]
	at com.ctc.wstx.sr.BasicStreamReader.next(BasicStreamReader.java:1180) ~[woodstox-core-6.5.1.jar:6.5.1]
	at com.fasterxml.jackson.dataformat.xml.XmlFactory._initializeXmlReader(XmlFactory.java:729) ~[jackson-dataformat-xml-2.15.2.jar:2.15.2]
	at com.fasterxml.jackson.dataformat.xml.XmlFactory._createParser(XmlFactory.java:600) ~[jackson-dataformat-xml-2.15.2.jar:2.15.2]
	at com.fasterxml.jackson.dataformat.xml.XmlFactory._createParser(XmlFactory.java:30) ~[jackson-dataformat-xml-2.15.2.jar:2.15.2]
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:1143) ~[jackson-core-2.15.2.jar:2.15.2]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3809) ~[jackson-databind-2.15.2.jar:2.15.2]
	at fr.pilato.elasticsearch.crawler.fs.tika.XmlDocParser.asMap(XmlDocParser.java:80) ~[fscrawler-tika-2.10-SNAPSHOT.jar:?]
	... 7 more
Caused by: java.io.CharConversionException: Invalid UTF-8 middle byte 0xcf (at char #0, byte #-1)
	at com.ctc.wstx.io.UTF8Reader.reportInvalidOther(UTF8Reader.java:318) ~[woodstox-core-6.5.1.jar:6.5.1]
	at com.ctc.wstx.io.UTF8Reader.read(UTF8Reader.java:208) ~[woodstox-core-6.5.1.jar:6.5.1]
	at com.ctc.wstx.io.ReaderSource.readInto(ReaderSource.java:88) ~[woodstox-core-6.5.1.jar:6.5.1]
	at com.ctc.wstx.io.BranchingReaderSource.readInto(BranchingReaderSource.java:57) ~[woodstox-core-6.5.1.jar:6.5.1]
	at com.ctc.wstx.sr.StreamScanner.loadMore(StreamScanner.java:1011) ~[woodstox-core-6.5.1.jar:6.5.1]
	at com.ctc.wstx.sr.StreamScanner.getNext(StreamScanner.java:770) ~[woodstox-core-6.5.1.jar:6.5.1]
	at com.ctc.wstx.sr.BasicStreamReader.nextFromProlog(BasicStreamReader.java:2096) ~[woodstox-core-6.5.1.jar:6.5.1]
	at com.ctc.wstx.sr.BasicStreamReader.next(BasicStreamReader.java:1180) ~[woodstox-core-6.5.1.jar:6.5.1]
	at com.fasterxml.jackson.dataformat.xml.XmlFactory._initializeXmlReader(XmlFactory.java:729) ~[jackson-dataformat-xml-2.15.2.jar:2.15.2]
	at com.fasterxml.jackson.dataformat.xml.XmlFactory._createParser(XmlFactory.java:600) ~[jackson-dataformat-xml-2.15.2.jar:2.15.2]
	at com.fasterxml.jackson.dataformat.xml.XmlFactory._createParser(XmlFactory.java:30) ~[jackson-dataformat-xml-2.15.2.jar:2.15.2]
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:1143) ~[jackson-core-2.15.2.jar:2.15.2]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3809) ~[jackson-databind-2.15.2.jar:2.15.2]
	at fr.pilato.elasticsearch.crawler.fs.tika.XmlDocParser.asMap(XmlDocParser.java:80) ~[fscrawler-tika-2.10-SNAPSHOT.jar:?]
	... 7 more
```

**Expected behavior**

- The file gets parsed correctly.
- That the other files that did not have issues are parsed.

**Versions:**
(I am using docker though)
 - OS: MacOS
 - Version: 13.6

**Comment by dadoonet** [comment] 2024-01-30 13:40
Is your platform running with `UTF-8`? 
Do you have a file you could share to reproduce the problem?

**Comment by HansBambel** [comment] 2024-01-31 16:25
I can't reproduce the error... I am getting another error when I am looking at the logs. Every xml that I have gets the error `field name cannot be an empty string`. Here is the log:

```
16:00:23,716 [30mTRACE[m [f.p.e.c.f.c.ElasticsearchClient] POST https://opensearch-node1:9200/_bulk gives {"took":14,"errors":true,"items":[{"index":{"_index":"sample_files","_id":"audatex sample cleaned.xml","status":400,"error":{"type":"mapper_parsing_exception","reason":"failed to parse","caused_by":{"type":"illegal_argument_exception","reason":"field name cannot be an empty string"}}}}]}
16:00:23,718 [36mDEBUG[m [f.p.e.c.f.f.b.FsCrawlerSimpleBulkProcessorListener] Executed bulk composed of 1 actions
16:00:23,720 [33mWARN [m [f.p.e.c.f.f.b.FsCrawlerSimpleBulkProcessorListener] There was failures while executing bulk
java.lang.RuntimeException: ElasticsearchOperation{operation=INDEX, index='sample_files', id='audatex sample cleaned.xml'}:ElasticsearchOperation{operation=INDEX, index='sample_files', id='audatex sample cleaned.xml'}:failed to parse
1 failures
	at fr.pilato.elasticsearch.crawler.fs.framework.bulk.FsCrawlerBulkResponse.buildFailureMessage(FsCrawlerBulkResponse.java:71) ~[fscrawler-framework-2.10-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.client.ElasticsearchBulkResponse.buildFailureMessage(ElasticsearchBulkResponse.java:64) ~[fscrawler-elasticsearch-client-2.10-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.framework.bulk.FsCrawlerSimpleBulkProcessorListener.afterBulk(FsCrawlerSimpleBulkProcessorListener.java:43) ~[fscrawler-framework-2.10-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.framework.bulk.FsCrawlerAdvancedBulkProcessorListener.afterBulk(FsCrawlerAdvancedBulkProcessorListener.java:48) ~[fscrawler-framework-2.10-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.framework.bulk.FsCrawlerRetryBulkProcessorListener.afterBulk(FsCrawlerRetryBulkProcessorListener.java:51) ~[fscrawler-framework-2.10-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.framework.bulk.FsCrawlerBulkProcessor.execute(FsCrawlerBulkProcessor.java:148) ~[fscrawler-framework-2.10-SNAPSHOT.jar:?]
	at fr.pilato.elasticsearch.crawler.fs.framework.bulk.FsCrawlerBulkProcessor.executeWhenNeeded(FsCrawlerBulkProcessor.java:133) ~[fscrawler-framework-2.10-SNAPSHOT.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
16:00:23,738 [36mDEBUG[m [f.p.e.c.f.f.b.FsCrawlerSimpleBulkProcessorListener] Error for [ElasticsearchOperation{operation=INDEX, index='sample_files', id='audatex sample cleaned.xml'}]: failed to parse
16:00:23,738 [33mWARN [m [f.p.e.c.f.f.b.FsCrawlerAdvancedBulkProcessorListener] Throttling is activated. Got [0] successive errors so far.
```

I am currently waiting for a green light to share a pseudomized file. Will share it as soon as I have this.

**Comment by dadoonet** [comment] 2024-01-31 16:49
Yeah thanks. I'd need to have one file to check why it does not work. I'm suspected an unexpected XML content...

**Comment by HansBambel** [comment] 2024-02-05 07:20
@dadoonet May I send it to you privately? I did not get the green light to upload it to Github.

**Comment by dadoonet** [comment] 2024-02-05 08:56
Sure.

**Comment by dadoonet** [comment] 2024-02-09 18:58
I looked at how the XML you sent me is converted to JSON.

The problem is with that kind of content:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Task>
 <Tag attr="false">Content</Tag>
</Task>
```

This is generating the following json:

```json
{
  "Tag": {
     "attr":"false",
     "":"Content"
  }
}
```

See the empty field name? Elasticsearch can not allow that obviously.
I will try to see if I can fix such a case with some jackson settings.

**Comment by HansBambel** [comment] 2024-02-10 06:44
Interesting. Thank you for the find!

**Comment by dadoonet** [comment] 2024-02-10 14:27
Same issue reported at https://github.com/FasterXML/jackson-dataformat-xml/issues/127

I'm trying to find a workaround now.

**Comment by dadoonet** [comment] 2024-02-10 14:56
This should be fixed now. Please try the latest build from today when it will be available ;)

**Closed** 2024-02-10 14:55 UTC
Labels: bug

**Comment by HansBambel** [comment] 2024-02-10 20:23
Thank you! I will test it next week!

**Comment by HansBambel** [comment] 2024-02-12 07:41
I just tested it and it works! No more errors 👍 

Two things I noticed though: Only 4 different files from my folder structure were parsed. Could it be that the file-name is the reason here? The folder-structure and naming is the following:
```
- sample_files
  - folder_1
    - file.xml
    - file.doc
  - folder_2
    - file.xml
    - file.doc
  - folder_3
    - file.xml
    - file.doc
```

Additionally, only `.xml` and no `.doc` files got parsed even though I specified that both kind should be parsed.

**Comment by HansBambel** [comment] 2024-02-12 09:31
Good to know, thanks! 
I created another job just for doc + docx files and that seemed to do the trick when I ran them with `xml_support: false` and after each other.

I now have two configs in my config-folder: `sample_files_doc` and `sample_files_xml`. In both of them I set `name: "sample_files"` in the `_settings.yaml`. This seems to work and adds all parsed files to the index `sample_files`.
Do I understand it correctly that `name` is for specifying the `index` in Elastic/Opensearch? I thought it must have been the same as the config-folder name. 

Also: is it possible to run both jobs simultaneously with a single fscrawler instance? Like so: 
```fscrawler --trace --restart sample_files_doc sample_files_xml```

**Comment by dadoonet** [comment] 2024-02-12 09:39
> I now have two configs in my config-folder: `sample_files_doc` and `sample_files_xml`. In both of them I set `name: "sample_files"` in the `_settings.yaml`. This seems to work and adds all parsed files to the index `sample_files`.
> Do I understand it correctly that `name` is for specifying the `index` in Elastic/Opensearch?

Yes. We are using the `name` field. But you can overwrite it using https://fscrawler.readthedocs.io/en/latest/admin/fs/elasticsearch.html#index-settings



> Also: is it possible to run both jobs simultaneously with a single fscrawler instance? Like so:
> `fscrawler --trace --restart sample_files_doc sample_files_xml`

Not yet sadly. We need to implement first multithreading and something like: #399

**Comment by HansBambel** [comment] 2024-02-12 09:56
> Yes. We are using the name field. But you can overwrite it using https://fscrawler.readthedocs.io/en/latest/admin/fs/elasticsearch.html#index-settings

Okay, but according to the documentation shouldn't it be then `sample_files_doc`, because "(name property) plus _doc suffix"?

> We need to implement first multithreading and something like: https://github.com/dadoonet/fscrawler/issues/399

Thanks for the info!

**Comment by dadoonet** [comment] 2024-02-12 18:04
> Okay, but according to the documentation shouldn't it be then sample_files_doc, because "(name property) plus _doc suffix"?

Damn! I think this change never happened... I'd qualify this as a documentation issue or as a work in progress... 😛 
Would you like to open an issue to fix the documentation? Or better a PR?

**Comment by HansBambel** [comment] 2024-02-13 08:13
Sure! I know the pain of keeping the documentation up to date ;)
