### ISSUE TITLE
Failing to create index in Elastic Cloud (fscrawler 2.2)

### ISSUE THREAD

**Issue by FrodeRennemo** [dadoonet/fscrawler#233] opened 2016-10-18 07:36 UTC
Hi,

I'm able to use the crawler successfully on localhost, but now we're moving the index to Elastic Cloud(5.0 RC1).

<b>Settings(user,pw and host not here)</b>

```
{
  "name" : "cloud",
  "fs" : {
    "url" : "C:/Test/articles",
    "update_rate" : "15m",
    "json_support" : true,
    "filename_as_id" : false,
    "add_filesize" : true,
    "remove_deleted" : true,
    "store_source" : false,
    "index_content" : true,
    "attributes_support" : false,
    "raw_metadata" : true,
    "xml_support" : false
  },
  "elasticsearch" : {
    "username" : "",
    "password" : "",
    "nodes" : [ {
      "host" : "",
      "port" : 9200
    } ],
    "type" : "doc",
    "bulk_size" : 100,
    "flush_interval" : "5s"
  }
}
```

<b>Running with trace </b>

```
09:17:56,279 DEBUG [f.p.e.c.f.u.FsCrawlerUtil] Copying [1/doc.json]...
09:17:56,279 DEBUG [f.p.e.c.f.u.FsCrawlerUtil] Copying [1/folder.json]...
09:17:56,279 DEBUG [f.p.e.c.f.u.FsCrawlerUtil] Copying [2/doc.json]...
09:17:56,279 DEBUG [f.p.e.c.f.u.FsCrawlerUtil] Copying [2/folder.json]...
09:17:56,279 DEBUG [f.p.e.c.f.u.FsCrawlerUtil] Copying [5/doc.json]...
09:17:56,279 DEBUG [f.p.e.c.f.u.FsCrawlerUtil] Copying [5/folder.json]...
09:17:56,294 DEBUG [f.p.e.c.f.FsCrawler] Starting job [cloud]...
09:17:56,379 TRACE [f.p.e.c.f.FsCrawler] settings used for this crawler: [{
  "name" : "cloud",
  "fs" : {
    "url" : "C:/Test/articles",
    "update_rate" : "15m",
    "json_support" : true,
    "filename_as_id" : false,
    "add_filesize" : true,
    "remove_deleted" : true,
    "store_source" : false,
    "index_content" : true,
    "attributes_support" : false,
    "raw_metadata" : true,
    "xml_support" : false
  },
  "elasticsearch" : {
    "nodes" : [ {
      "host" : "",
      "port" : 9200
    } ],
    "type" : "doc",
    "bulk_size" : 100,
    "flush_interval" : "5s",
    "username" : "",
    "password" : ""
  }
}]
09:17:56,379 INFO  [f.p.e.c.f.FsCrawlerImpl] Starting FS crawler
09:17:56,379 INFO  [f.p.e.c.f.FsCrawlerImpl] FS crawler started in watch mode. It will run unless you stop it with CTRL+C.
09:17:56,657 DEBUG [f.p.e.c.f.c.ElasticsearchClient] create index [cloud]
09:17:57,715 WARN  [f.p.e.c.f.FsCrawlerImpl] failed to create index [cloud], disabling crawler...
09:17:57,715 FATAL [f.p.e.c.f.FsCrawler] Fatal error received while running the crawler: [null]
09:17:57,715 DEBUG [f.p.e.c.f.FsCrawler] error caught
java.net.ConnectException
        at org.apache.http.nio.pool.RouteSpecificPool.timeout(RouteSpecificPool.java:168) ~[httpcore-nio-4.4.5.jar:4.4.5]
        at org.apache.http.nio.pool.AbstractNIOConnPool.requestTimeout(AbstractNIOConnPool.java:561) ~[httpcore-nio-4.4.5.jar:4.4.5]
        at org.apache.http.nio.pool.AbstractNIOConnPool$InternalSessionRequestCallback.timeout(AbstractNIOConnPool.java:822) ~[httpcore-nio-4.4.5.jar:4.4.5]
        at org.apache.http.impl.nio.reactor.SessionRequestImpl.timeout(SessionRequestImpl.java:183) ~[httpcore-nio-4.4.5.jar:4.4.5]
        at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processTimeouts(DefaultConnectingIOReactor.java:210) ~[httpcore-nio-4.4.5.jar:4.4.5]
        at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:155) ~[httpcore-nio-4.4.5.jar:4.4.5]
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:348) ~[httpcore-nio-4.4.5.jar:4.4.5]
        at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:192) ~[httpasyncclient-4.1.2.jar:4.1.2]
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64) ~[httpasyncclient-4.1.2.jar:4.1.2]
        at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_102]
09:17:57,730 DEBUG [f.p.e.c.f.FsCrawlerImpl] Closing FS crawler [cloud]
09:17:57,730 DEBUG [f.p.e.c.f.c.ElasticsearchClient] Closing REST client
```

Putting "http://" in front of host returns UnknownHostException. I have also tried using the https endpoint but the same error occurs. 

Any idea what's causing this?

**Comment by dadoonet** [comment] 2016-10-18 07:57
> Any idea what's causing this?

Nope. And that's a shame I never tested it with cloud.elastic.co service! 
Thanks for opening it. I'll try to look at it as soon as I can.

Just to make sure about your settings, you tried something like 

```json
{
  "name" : "job_name",
  "fs" : {
    "url" : "/path/to/data/dir"
  },
  "elasticsearch" : {
    "nodes" : [ {
      "host" : "YOURCLUSTERID.eu-west-1.aws.found.io",
      "port" : 9200
    } ],
    "username" : "username",
    "password" : "password"
  }
}
```

Right?

**Comment by FrodeRennemo** [comment] 2016-10-18 08:14
Correct! But I don't understand why there should be any difference whether the cluster is hosted in Elastic Cloud or another remote machine? That being said I should try to test with another host, but I don't have anything available to test with.

**Comment by dadoonet** [comment] 2016-10-18 09:32
No idea. Network timeout? Proxy? That's why I want to test it and BTW add support for https.

**Comment by dadoonet** [comment] 2016-12-23 17:15
@FrodeRennemo So I just tested the full test suite against a cloud instance (using the new #254 test feature) and everything worked fine.

Note that I tested with HTTP, not HTTPS.

I'm closing as I can't reproduce. Feel free to reopen if you have more details.

**Closed by dadoonet** 2016-12-23 17:15 UTC
Labels: bug
