### ISSUE TITLE
Modifying folder path location does not remove old location

### ISSUE THREAD

**Issue by christopherjm** [dadoonet/fscrawler#244] opened 2016-11-11 14:20 UTC
I am using fscrawler 2.1 on Mac 10.11.6, when I modify the folder name where a document is under, Elasticsearch caches the new file with the new location (as expected), but it does not remove the old one. 
i.e.
Search for 'Java'

1. Java for beginners
users/documents/oldpath/books

2. Java for beginners
users/documents/newpath/books

I am expecting that #1 wont show. Any thing i missed?

**Comment by dadoonet** [comment] 2017-01-31 17:21
I guess you did not change `remove_deleted` default option (true), right? https://github.com/dadoonet/fscrawler#ignore-deleted-files

In such a case, I think this should be handled by fscrawler but I know I had some issue in 2.1.
Any chance you can try 2.2-SNAPSHOT (the readme gives a link to download it).

Thanks! (And sorry for the delay)

**Comment by dadoonet** [comment] 2017-01-31 17:29
Might be caused by #95 actually. So I'm closing it in favor of #95.

**Closed by dadoonet** 2017-01-31 17:29 UTC
