### ISSUE TITLE
Image content crawling does not work

### ISSUE THREAD

**Issue by denisallardarmor** [dadoonet/fscrawler#1480] opened 2022-08-24 13:07 UTC
**Describe the bug**

Hi ! 

I'm using the latest docker image as of today :
> dadoonet/fscrawler@sha256:5ea5286b37d49749a636790a228c16f65ef5bd69eb10f566bc894c7d45b19360

When using `.txt /.pdf / .doc` files I am able to index content as text.

But when using `.png / .jpg` files I can't analyze content pushing file with the API or via scheduled job.

I understand that Tesseract is the one to provide this feature and it seems that I'm missing some configuration on this part but logs are saying it's ok : `OCR strategy for PDF documents is [auto] and tesseract was found`.

When I push a file using API using the command below :

```bash
curl -F "file=@img-test-document-3.jpg" "http://my-machine-fscrawler:8080/fscrawler/_document?debug=true&simulate=true"
```

I get this result that does not contain `_source.content` :

```json
{
  "ok" : true,
  "filename" : "img-test-document-3.jpg",
  "url" : "http://my-machine-elk-stack:9200/job_name/_doc/6ab65eaa25689547070158d3e111399",
  "doc" : {
    "meta" : { },
    "file" : {
      "extension" : "jpg",
      "content_type" : "image/jpeg",
      "indexing_date" : "2022-08-24T12:41:25.644+00:00",
      "filename" : "img-test-document-3.jpg"
    },
    "path" : {
      "virtual" : "img-test-document-3.jpg",
      "real" : "img-test-document-3.jpg"
    }
  }
```

**Job Settings**

```yml
---
name: "job_name"
fs:
  url: "/tmp/es"
  update_rate: "15m"
  excludes:
  - "*/~*"
  json_support: false
  filename_as_id: false
  add_filesize: true
  remove_deleted: true
  add_as_inner_object: false
  store_source: false
  index_content: true
  attributes_support: false
  raw_metadata: false
  xml_support: false
  index_folders: true
  lang_detect: false
  continue_on_error: false
  ocr:
    path: "/usr/bin"
    data_path: "/usr/share/tesseract-ocr/4.00/tessdata"
    output_type: "txt" 
    language: "eng"
    enabled: true
    pdf_strategy: "auto"
  follow_symlinks: false
elasticsearch:
  nodes:
  - url: "http://my-machine-elk-stack:9200"
  bulk_size: 100
  flush_interval: "5s"
  byte_size: "10mb"
  ssl_verification: true
rest:
  url: "http://0.0.0.0:8080/fs"
  enable_cors: true
```

**Logs**

```
root@569de8f4de74:/usr/share/fscrawler# /usr/bin/fscrawler job_name --loop 0 --rest --debug
12:40:59,136 INFO  [f.p.e.c.f.c.BootstrapChecks] Memory [Free/Total=Percent]: HEAP [177.8mb/2.9gb=5.95%], RAM [354.7mb/11.6gb=2.97%], Swap [0b/0b=0.0].
12:40:59,138 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [6/_settings.json] already exists
12:40:59,138 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [6/_settings_folder.json] already exists
12:40:59,139 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [7/_settings.json] already exists
12:40:59,139 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [7/_settings_folder.json] already exists
12:40:59,140 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [7/_wpsearch_settings.json] already exists
12:40:59,140 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [8/_settings.json] already exists
12:40:59,140 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [8/_settings_folder.json] already exists
12:40:59,141 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [8/_wpsearch_settings.json] already exists
12:40:59,142 DEBUG [f.p.e.c.f.c.FsCrawlerCli] Starting job [job_name]...
12:40:59,497 INFO  [f.p.e.c.f.FsCrawlerImpl] Starting FS crawler
12:40:59,548 DEBUG [f.p.e.c.f.c.ElasticsearchClient] get version
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions prior to 1.8.
SLF4J: Ignoring binding found at [jar:file:/usr/share/fscrawler/lib/log4j-slf4j-impl-2.18.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#ignoredBindings for an explanation.
12:41:00,029 DEBUG [f.p.e.c.f.c.ElasticsearchClient] get version returns 8.3.3 and 8 as the major version number
12:41:00,029 INFO  [f.p.e.c.f.c.ElasticsearchClient] Elasticsearch Client connected to a node running version 8.3.3
12:41:00,035 DEBUG [f.p.e.c.f.s.FsCrawlerManagementServiceElasticsearchImpl] Elasticsearch Management Service started
12:41:00,039 DEBUG [f.p.e.c.f.c.ElasticsearchClient] get version
12:41:00,084 DEBUG [f.p.e.c.f.c.ElasticsearchClient] get version returns 8.3.3 and 8 as the major version number
12:41:00,084 INFO  [f.p.e.c.f.c.ElasticsearchClient] Elasticsearch Client connected to a node running version 8.3.3
12:41:00,085 DEBUG [f.p.e.c.f.s.FsCrawlerDocumentServiceElasticsearchImpl] Elasticsearch Document Service started
12:41:00,086 DEBUG [f.p.e.c.f.c.ElasticsearchClient] create index [job_name]
12:41:00,101 DEBUG [f.p.e.c.f.c.ElasticsearchClient] Error while running PUT http://my-machine-elk-stack:9200/job_name: {"error":{"root_cause":[{"type":"resource_already_exists_exception","reason":"index [job_name/HsciFwtWRoG0oRtDoO1kzg] already exists","index_uuid":"HsciFwtWRoG0oRtDoO1kzg","index":"job_name"}],"type":"resource_already_exists_exception","reason":"index [job_name/HsciFwtWRoG0oRtDoO1kzg] already exists","index_uuid":"HsciFwtWRoG0oRtDoO1kzg","index":"job_name"},"status":400}
12:41:00,101 DEBUG [f.p.e.c.f.c.ElasticsearchClient] Response for create index [job_name]: HTTP 400 Bad Request
12:41:00,104 DEBUG [f.p.e.c.f.c.ElasticsearchClient] create index [job_name_folder]
12:41:00,109 DEBUG [f.p.e.c.f.c.ElasticsearchClient] Error while running PUT http://my-machine-elk-stack:9200/job_name_folder: {"error":{"root_cause":[{"type":"resource_already_exists_exception","reason":"index [job_name_folder/Jwa6riLuQAykwo888Mz7IQ] already exists","index_uuid":"Jwa6riLuQAykwo888Mz7IQ","index":"job_name_folder"}],"type":"resource_already_exists_exception","reason":"index [job_name_folder/Jwa6riLuQAykwo888Mz7IQ] already exists","index_uuid":"Jwa6riLuQAykwo888Mz7IQ","index":"job_name_folder"},"status":400}
12:41:00,110 DEBUG [f.p.e.c.f.c.ElasticsearchClient] Response for create index [job_name_folder]: HTTP 400 Bad Request
12:41:00,113 DEBUG [f.p.e.c.f.FsParserNoop] Fs crawler is going to sleep for 15m
12:41:00,285 WARN  [o.g.j.s.w.WadlFeature] JAXBContext implementation could not be found. WADL feature is disabled.
12:41:00,368 WARN  [o.g.j.i.i.Providers] A provider fr.pilato.elasticsearch.crawler.fs.rest.ServerStatusApi registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider fr.pilato.elasticsearch.crawler.fs.rest.ServerStatusApi will be ignored. 
12:41:00,368 WARN  [o.g.j.i.i.Providers] A provider fr.pilato.elasticsearch.crawler.fs.rest.UploadApi registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider fr.pilato.elasticsearch.crawler.fs.rest.UploadApi will be ignored. 
12:41:00,369 WARN  [o.g.j.i.i.Providers] A provider fr.pilato.elasticsearch.crawler.fs.rest.DocumentApi registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider fr.pilato.elasticsearch.crawler.fs.rest.DocumentApi will be ignored. 
12:41:00,557 INFO  [f.p.e.c.f.r.RestServer] FS crawler Rest service started on [http://0.0.0.0:8080/fs]
12:41:25,636 DEBUG [f.p.e.c.f.r.RestApi] uploadToDocumentService(true, true, null, null, ...)
12:41:25,656 DEBUG [f.p.e.c.f.t.TikaInstance] OCR is activated so we need to configure Tesseract in case we have specific settings.
12:41:25,658 DEBUG [f.p.e.c.f.t.TikaInstance] Tesseract Language set to [eng].
12:41:25,659 DEBUG [f.p.e.c.f.t.TikaInstance] Tesseract Output Type set to [txt].
12:41:25,669 DEBUG [f.p.e.c.f.t.TikaInstance] OCR is activated.
12:41:25,673 DEBUG [f.p.e.c.f.t.TikaInstance] Tesseract Path set to [/usr/bin].
12:41:25,674 DEBUG [f.p.e.c.f.t.TikaInstance] Tesseract Data Path set to [/usr/share/tesseract-ocr/4.00/tessdata].
12:41:25,703 DEBUG [f.p.e.c.f.t.TikaInstance] OCR strategy for PDF documents is [auto] and tesseract was found.
12:41:25,703 INFO  [f.p.e.c.f.t.TikaInstance] OCR is enabled. This might slowdown the process.
12:41:26,380 DEBUG [f.p.e.c.f.r.RestApi] Simulate mode is on, so we skip sending document [img-test-document-3.jpg] to elasticsearch at [http://my-machine-elk-stack:9200/job_name/_doc/6ab65eaa25689547070158d3e111399].
```

**Expected behavior**

I expect fscrawler to analyze the content of the image and provide `_source.content` as text while indexing image using tesseract.

**Versions:**
 - OS: Ubuntu 20.04.4 LTS
 - Version : 2.10-SNAPSHOT

**Attachment**

The image used contains an english comment from one of this repo issues.

![img-test-document-3](https://user-images.githubusercontent.com/50982921/186425254-9308d206-417e-4185-9830-4f41b9ec3795.jpg)

Thank you !

**Comment by dadoonet** [comment] 2022-08-25 13:11
Hey @denisallardarmor 

Thanks for reporting. Could you share the `img-test-document-3.jpg` test file?

Could you also try to remove:

```
  ocr:
    path: "/usr/bin"
    data_path: "/usr/share/tesseract-ocr/4.00/tessdata"
    output_type: "txt" 
    language: "eng"
    enabled: true
    pdf_strategy: "auto"
```

from the job settings, and start again?

**Comment by denisallardarmor** [comment] 2022-08-25 13:40
Hi David, 

Thanks for your quick answer !

I removed the conf as told but it's still not giving a content.

You can find the image in the "Attachment" section of my first message, at the end.
Link is : https://user-images.githubusercontent.com/50982921/186425254-9308d206-417e-4185-9830-4f41b9ec3795.jpg

Thanks

**Comment by denisallardarmor** [comment] 2022-08-26 07:03
Ok !

I won't try to tweak my conf any longer :)

Thank you for your time and your timely answers.

Good luck !

**Comment by dadoonet** [comment] 2022-09-02 09:34
So this is caused by https://issues.apache.org/jira/browse/TIKA-3812

This will be fixed in the next Tika release...

**Comment by denisallardarmor** [comment] 2022-09-02 12:56
Alright, thank you !

**Comment by luca-ren** [comment] 2022-09-14 13:51
Hi David, 

Thank you for your work !

I was wondering if there is a version of fscrawler using tika 2.4.0 ? 
Or a version of Fscrawler  with support for Elasticsearch 8.x and a working crawler on images ?

Thank you

**Closed** 2022-10-04 14:11 UTC
Labels: bug
