### ISSUE TITLE
stackoverflow exception reported for 2.3 snapshot

### ISSUE THREAD

**Issue by cnddu** [dadoonet/fscrawler#369] opened 2017-05-17 06:54 UTC
Here is the log 
```
14:45:11,262 INFO  [f.p.e.c.f.FsCrawler] No job specified. Here is the list of existing jobs:
14:45:11,268 INFO  [f.p.e.c.f.FsCrawler] [1] - mdtest
14:45:11,268 INFO  [f.p.e.c.f.FsCrawler] Choose your job [1-1]...
1
14:45:20,145 INFO  [f.p.e.c.f.FsCrawlerImpl] Starting FS crawler
14:45:20,145 INFO  [f.p.e.c.f.FsCrawlerImpl] FS crawler started in watch mode. It will run unless you stop it with CTRL+C.
14:45:20,810 WARN  [o.e.c.RestClient] request [PUT http://127.0.0.1:9200/mdtest] returned 1 warnings: [299 Elasticsearch-5.4.0-780f8c4 "Content type detection for rest requests is deprecated. Specify the content type using the [Content-Type] header." "Wed, 17 May 2017 06:45:20 GMT"]
14:45:20,845 INFO  [f.p.e.c.f.FsCrawlerImpl] FS crawler started for [mdtest] for [/home/cmgc/docs] every [15m]
Exception in thread "fs-crawler" java.lang.StackOverflowError
	at java.lang.Exception.<init>(Exception.java:102)
	at java.lang.ReflectiveOperationException.<init>(ReflectiveOperationException.java:89)
	at java.lang.reflect.InvocationTargetException.<init>(InvocationTargetException.java:72)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2136)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2027)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2245)
	at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:552)
	at org.apache.http.impl.auth.RFC2617Scheme.readObject(RFC2617Scheme.java:166)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2136)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2027)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at org.apache.http.impl.client.BasicAuthCache.get(BasicAuthCache.java:130)
	at org.apache.http.client.protocol.RequestAuthCache.process(RequestAuthCache.java:107)
	at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:133)
	at org.apache.http.impl.nio.client.MainClientExec.prepareRequest(MainClientExec.java:520)
	at org.apache.http.impl.nio.client.MainClientExec.prepare(MainClientExec.java:146)
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.start(DefaultClientExchangeHandlerImpl.java:124)
	at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:141)
	at org.elasticsearch.client.RestClient.performRequestAsync(RestClient.java:343)
	at org.elasticsearch.client.RestClient.performRequestAsync(RestClient.java:325)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:218)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:191)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:170)
	at fr.pilato.elasticsearch.crawler.fs.client.ElasticsearchClient.search(ElasticsearchClient.java:278)
	at fr.pilato.elasticsearch.crawler.fs.client.ElasticsearchClient.search(ElasticsearchClient.java:251)
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.getFileDirectory(FsCrawlerImpl.java:471)
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.removeEsDirectoryRecursively(FsCrawlerImpl.java:675)
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.removeEsDirectoryRecursively(FsCrawlerImpl.java:686)
	at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.removeEsDirectoryRecursively(FsCrawlerImpl.java:686)

```

**Comment by dadoonet** [comment] 2017-05-17 07:18
Interesting. I indeed did some changes recently (cdafe0024a2b9ee1061aa3d20fb0a5b83abfc726) to fix #353 which might cause this.

Could you run a:

```sh
tree /home/cmgc/docs
```

So I can may be reproduce a similar dir layout within integration tests.

I'll look into it. Thanks for reporting!

**Comment by cnddu** [comment] 2017-05-17 15:22
thanks, but that folder only contains one txt file: test.txt.
```
[cmgc@iZ28vryf5hjZ ~]$ cat /home/cmgc/docs/test.txt 
测试一下搜索的效率
今天天气晴好
明天要上班了
[cmgc@iZ28vryf5hjZ ~]$ 
```

**Comment by dadoonet** [comment] 2017-05-18 09:25
So I did some tests on my side and I can't reproduce it.
I'm going to try with the file you pasted here.

**Comment by dadoonet** [comment] 2017-05-18 09:48
So I just added another test and I can't reproduce your problem.

Can you please run:

```sh
tree /home/cmgc/docs -a
```

Thanks!

**Comment by sekergws** [comment] 2017-06-06 15:53
Has this been solved ?

I have a similar problem running FSCrawler 2.2 and Elasticsearch-5.4.1-2cfe0df

[299 Elasticsearch-5.4.1-2cfe0df Content type detection for rest requests is deprecated. Specify the content type using the [Content-Type] header. Tue, 06 Jun 2017 14:46:15 GMT]

**Comment by dadoonet** [comment] 2017-06-06 15:57
@sekergws the log line you pasted is not related to a stackoverflow problem.
If you want to get rid of the log line, use the latest snapshot. The link is in the README.

**Comment by dadoonet** [comment] 2017-06-14 17:58
No more feedback. Closing. Feel free to reopen or comment if anything new.

**Closed by dadoonet** 2017-06-14 17:58 UTC
Labels: bug, wait for feedback
