### ISSUE TITLE
fscrawler overwriting config file?

### ISSUE THREAD

**Issue by paulbrowne-irl** [dadoonet/fscrawler#290] opened 2017-01-28 10:09 UTC
Folks,

Wondering if anybody else has come across an issue with fscrawler overwriting config files?

Able to install as a plugin, first time run 'fscrawler job_index_name' correctly asks then creates the _settings.json. Message (' Settings have been created in [C:\Users\pbrowne\.fscrawler]. Please review and edit before relaunch') I edit to include the username and password of my local Elasticsearch server.

However, when I run a 2nd time, I get the message ''job [job_index_name] does not exist Do you want to create it (Y/N)?' and will either not run (option N) or overwrite the file (option Y).

If I run fscrawler (with no job name) is correctly lists [job_index_name] as option 1. pressing 1 then gives the 'job does not exist' message as per above.

Running fscrawler 2.1 against elasticsearch 5.1.2, Java 1.8.0_121 on Windows 7. Sure it's something simple I've missed, any suggestions, or any more info that you need to help me on this?

Thanks

Paul

**Comment by dadoonet** [comment] 2017-01-28 10:52
I think it was a stupid mistake I made in 2.1.

Can you try 2.2-SNAPSHOT (you'll find the link in README, download section)?

**Comment by paulbrowne-irl** [comment] 2017-01-28 15:51
Thanks for that. Have downloaded the latest snapshot 2.2-20170124.213832-138, and this problem (overwriting of the config, no matter what the edit) is fixed.

I am seeing something that users should be aware of: if the _settings.json is not the exact format expected (e.g. I add the username and password in the wrong place, even if it is correct json format) then the fscrawler appears not to recognize and will still prompt to overwrite.

This is not an issue but something for users to be aware of when editing the _settions.json file. Will post when have completely working to confirm.

**Comment by dadoonet** [comment] 2017-01-28 18:34
Interesting. Is this also happening with 2.2?

**Comment by paulbrowne-irl** [comment] 2017-01-28 21:45
2.2 (snapshot) is where I've noticed this behaviour - wouldn't call it a bug, but a message warning that the file isn't in the format expected would help users.

In this case, was (incorrectly) putting the username & password immediately after the 'scheme' node, when it should follow the 'flush interval'. All valid json, but didn't match the config layout as detailed in the readme.md.

Just tried to recreate this by editing the _settings file back to what it was , to try and reproduce the error (and share an example file with you). But haven't been able to get the error again since it ran successfully.

**Comment by dadoonet** [comment] 2017-01-30 15:51
Can you share the incorrect setting files you used?
I can't reproduce what you saw. Basically I tried with `target/test/test/_settings.json` config file:

```json
{
  "name" : "test",
  "foo" : "bar"
}
```

Then starting with:

```sh
bin/fscrawler test --config_dir target/test
```

And it worked well. I mean that it simply ignored the wrong setting.

**Comment by dadoonet** [comment] 2017-01-30 15:53
Sounds like similar to #284. Going to try the example provided there.

**Comment by dadoonet** [comment] 2017-01-30 15:56
I tried also:

```json
{
  "name" : "test",
  "fs" : {
    "url" : "/root/files",
    "update_rate": "1m",
    "filename_as_id" : true,
    "store_source" : true,
    "indexed_chars": "100%"
  },
  "elasticsearch" : {
    "index" : "docker-fscrawler",
    "type": "doc",
    "nodes" : [
      { "host" : "127.0.0.1", "port" : 9200 }
    ],
    "bulksize": 100
  }
}
```

Then

```sh
bin/fscrawler test --config_dir target/test
```

Still can't reproduce with 2.2-SNAPSHOT.

**Comment by paulbrowne-irl** [comment] 2017-01-30 22:22
Ok.let me see if I can reproduce.

Paul

**Comment by dadoonet** [comment] 2017-01-30 22:29
I think you can reproduce but I feel like this is caused because you have something like a space in the `JAVA_HOME` or in your `PATH`.
That's why sharing your env vars could help.

**Comment by dadoonet** [comment] 2017-01-31 17:01
I think actually that I fixed the issue (not exactly the issue but kind of) with #295.
It now exits and gives a stacktrace of the problem.

I'm closing but feel free to reopen if you can reproduce with a recent SNAPSHOT.

**Closed by dadoonet** 2017-01-31 17:01 UTC
Labels: bug
