### ISSUE TITLE
excludes setting only works for endsWith wildcards / and files being edited with ~ are indexed

### ISSUE THREAD

**Issue by j-a-a-p** [dadoonet/fscrawler#1794] opened 2024-01-09 13:46 UTC
**Describe the bug**

Any exclude like

```yml
excludes:
- "~*"
```

will not work

[The code](https://github.com/dadoonet/fscrawler/blob/6850652c7d6c1fa16f9052e2e90af3bc0eff20e0/framework/src/main/java/fr/pilato/elasticsearch/crawler/fs/framework/FsCrawlerUtil.java#L211) is doing this a lazy replacement for the filter:

```java
String regex = exclude.toLowerCase().replace("?", ".?").replace("*", ".*?");
```

IF this is replaced by:

```java
String regex = exclude.toLowerCase().replace("?", ".?").replace("*", ".*");
```

the bug will be solved. Perhaps do this only when the exclude ends with '*'

**Comment by dadoonet** [comment] 2024-01-14 14:06
So I found the problem.

`~*` does not match a filename like `/~foo`.
The right syntax to use here is `*/~*` which should match. 

That's BTW the default value used for exclusions.

So it's not a bug to me but a misconfiguration.

Closing but feel free to reopen if needed.

**Closed by dadoonet** 2024-01-14 14:06 UTC
