### ISSUE TITLE
Links in docs for fscrawler 2.7 not working

### ISSUE THREAD

**Issue by geekyogurt** [dadoonet/fscrawler#824] opened 2019-10-04 05:01 UTC
The links given in the documentation for fscrawler 2.7 are not working. I am using elastic search 7.3.2 and no other fscrawler version is compatible with this version of elastic search.

**Comment by dadoonet** [comment] 2019-10-04 05:20
Thanks for reporting. Sounds like an access problem on Sonatype. I'll check this.

**Comment by dadoonet** [comment] 2019-10-04 08:17
I asked on [Twitter](https://twitter.com/dadoonet/status/1180033854196854786)... Let's see if something happens. cc @sonatype

**Comment by dadoonet** [comment] 2019-10-07 09:48
The problem is fixed now. Thanks for reporting.

**Closed by dadoonet** 2019-10-07 09:48 UTC
